'''drawn from Gloria github: https://github.com/marshuang80/gloria
'''

BERT_TYPE = 'emilyalsentzer/Bio_ClinicalBERT'
VIT_TYPE = 'microsoft/swin-tiny-patch4-window7-224'

IMG_SIZE = 256
IMG_MEAN = .2344
IMG_STD = .1946

UWMADISON_TASKS = [
    "No Finding",
    'mass',
    'features', 
    'calcification', 
    'asymmetry', 
    'surgical change', 
    'distortion', 
    'fatty', 
    'scattered fibroglandular density',
    'heterogeneously dense', 
    'extreme dense', 
    'lesion', 
    'implant'
]

# following prompts added by AU

UWMADISON_CLASS_PROMPTS = {
    "mass": {
        "severity": [""],
        "subtype": ['mass',
                    'round, obscured, oval, circumscribed',
                    'oval, circumscribed',
                    'oval',
                    'possible',
                    'round, circumscribed',
                    'obscured, oval',
                    'circumscribed',
                    'obscured, round',
                    'node',
                    'round',
                    'irregular',
                    'oval, indistinct',
                    'oval, circumscribed, equal density',
                    'round, circumscribed, equal density',
                    'equal density',
                    'node, oval, circumscribed',
                    'spiculated, irregular',
                    'oval, equal density',
                    'obscured',
                    'obscured, possible',
                    'round, oval, circumscribed',
                    'round, indistinct',
                    'node, round, circumscribed',
                    'obscured, circumscribed',
                    'node, circumscribed',
                    'circumscribed, irregular',
                    'round, oval',
                    'fat-containing',
                    'node, oval',
                    'oval, high density',
                    'obscured, oval, circumscribed',
                    'spiculated, round',
                    'oval, circumscribed, high density',
                    'microlobulated',
                    'obscured, round, circumscribed, equal density',
                    'obscured, round, oval, circumscribed, node',
                    'oval, circumscribed, possible',
                    'obscured, irregular',
                    'low density, oval, circumscribed',
                    'low density, circumscribed',
                    'microlobulated, irregular',
                    'irregular, possible, high density',
                    'round, irregular',
                    'microlobulated, oval, high density',
                    'round, obscured, spiculated, oval',
                    'round, circumscribed, possible',
                    'irregular, equal density',
                    'obscured, round, circumscribed',
                    'node, possible',
                    'round, circumscribed, high density',
                    'irregular, oval, indistinct',
                    'round, high density',
                    'obscured, oval, equal density',
                    'node, oval, possible',
                    'circumscribed, possible',
                    'microlobulated, oval, circumscribed',
                    'irregular, indistinct',
                    'microlobulated, spiculated',
                    'circumscribed, equal density',
                    'obscured, oval, possible',
                    'possible, irregular',
                    'microlobulated, round',
                    'low density, oval',
                    'fat-containing, oval',
                    'obscured, irregular, high density',
                    'round, oval, circumscribed, possible',
                    'obscured, oval, circumscribed, equal density',
                    'microlobulated, obscured, oval',
                    'round, oval, circumscribed, equal density',
                    'indistinct',
                    'round, circumscribed, indistinct',
                    'nodul, nodule, round, circumscribed',
                    'round, equal density'
                ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "features": {
        "severity": [""],
        "subtype": ['lymph node',
                    'architectural distortion',
                    'intramammary node',
                    'skin lesion',
                    'skin thickening',
                    'trabecular thickening',
                    'lymph node, intramammary node',
                    'nipple retraction',
                    'lymph node, architectural distortion',
                    'skin thickening, trabecular thickening',
                    'architectural distortion, trabecular thickening',
                    'lymph node, skin thickening',
                    'solitary dilated duct',
                    'nipple retraction, architectural distortion',
                    'skin retraction'
                ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "calcification": {
        "severity": [""],
        "subtype": ['benign calcification',
                    'benign calcification, vascular',
                    'grouped',
                    'diffuse, benign calcification',
                    'amorphous, grouped',
                    'grouped, benign calcification',
                    'dystrophic, benign calcification',
                    'vascular',
                    'amorphous',
                    'linear',
                    'dystrophic',
                    'diffuse',
                    'segmental',
                    'grouped, round',
                    'regional',
                    'round',
                    'skin',
                    'fine pleomorphic',
                    'linear, benign calcification',
                    'round, benign calcification',
                    'skin, benign calcification',
                    'grouped, fine-linear, linear',
                    'rim',
                    'diffuse, grouped',
                    'grouped, fine pleomorphic',
                    'grouped, linear',
                    'amorphous, regional',
                    'popcorn',
                    'diffuse, grouped, benign calcification',
                    'popcorn, benign calcification',
                    'grouped, benign calcification, vascular',
                    'grouped, round, benign calcification',
                    'linear, vascular',
                    'round, regional',
                    'segmental, grouped, linear',
                    'amorphous, grouped, benign calcification',
                    'large',
                    'rim, benign calcification',
                    'segmental, linear',
                    'milk of calcium',
                    'rod-like, benign calcification',
                    'segmental, fine-linear, linear',
                    'large, popcorn, benign calcification',
                    'dystrophic, grouped',
                    'large, benign calcification',
                    'dystrophic, rim, benign calcification',
                    'fine-linear, linear',
                    'grouped, linear, fine pleomorphic',
                    'grouped, linear, vascular',
                    'amorphous, benign calcification',
                    'benign calcification, coarse heterogenous',
                    'amorphous, grouped, round',
                    'diffuse, fine pleomorphic',
                    'segmental, benign calcification',
                    'round, diffuse, dystrophic, segmental, benign calcification, fine '
                    'pleomorphic',
                    'dystrophic, large',
                    'rim, grouped, benign calcification',
                    'large, linear, benign calcification',
                    'large, regional',
                    'vascular, grouped, benign calcification, regional',
                    'skin, round, benign calcification',
                    'milk of calcium, benign calcification'
                ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "asymmetry": {
        "severity": [""],
        "subtype": ['focal asymmetry',
                    'asymmetry',
                    'developing asymmetry',
                    'focal developing asymmetry',
                    'global asymmetry',
                    'questioned asymmetry'
                ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "surgical change": {
        "severity": [""],
        "subtype": ['biopsy clip',
                    'lumpectomy',
                    'implant',
                    'post operative finding',
                    'reduction',
                    'biopsy clip lumpectomy',
                    'biopsy clip implant',
                    'reduction biopsy clip',
                    'reduction lumpectomy',
                    'lumpectomy implant',
                    'reduction implant',
                    'reduction biopsy clip lumpectomy',
                    'reduction biopsy',
                    'biopsy clip lumpectomy implant',
                    'reduction clip',
                    'reduction lumpectomy implant',
                    'reduction biopsy lumpectomy',
                    'reduction clip lumpectomy',
                    'biopsy lumpectomy implant',
                    'clip lumpectomy implant'
                ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "distortion": {
        "severity": [""],
        "subtype": ["architectural distortion"],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "No Finding": {
        "severity": [""],
        "subtype": [""],
        "location": [""],
    },
    "fatty": {
        "severity": [""],
        "subtype": [""],
        "location": [""],
    },
    "scattered fibroglandular density": {
        "severity": [""],
        "subtype": [""],
        "location": [""],
    },
    "heterogeneously dense": {
        "severity": [""],
        "subtype": [""],
        "location": [""],
    },
    "extreme dense": {
        "severity": [""],
        "subtype": [""],
        "location": [""],
    },
    "lesion": {
        "severity": [""],
        "subtype": ["skin lesion", "fat necrosis", "cyst"],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
    "implant": {
        "severity": [""],
        "subtype": ["implant", 
                    "reduction implant", 
                    "biopsy clip implant", 
                    "clip lumpectomy implant"
        ],
        "location": ["in left breast", "in right breast", "in both breasts"],
    },
  
}



CHEXPERT_TASKS = [
    "No Finding",
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Lesion",
    "Lung Opacity",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
]
CHEXPERT_COMPETITION_TASKS = [
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Pleural Effusion",
]
CHEXPERT_CLASS_PROMPTS = {
    "Atelectasis": {
        "severity": ["", "mild", "minimal"],
        "subtype": [
            "subsegmental atelectasis",
            "linear atelectasis",
            "trace atelectasis",
            "bibasilar atelectasis",
            "retrocardiac atelectasis",
            "bandlike atelectasis",
            "residual atelectasis",
        ],
        "location": [
            "at the mid lung zone",
            "at the upper lung zone",
            "at the right lung zone",
            "at the left lung zone",
            "at the lung bases",
            "at the right lung base",
            "at the left lung base",
            "at the bilateral lung bases",
            "at the left lower lobe",
            "at the right lower lobe",
        ],
    },
    "Cardiomegaly": {
        "severity": [""],
        "subtype": [
            "cardiac silhouette size is upper limits of normal",
            "cardiomegaly which is unchanged",
            "mildly prominent cardiac silhouette",
            "portable view of the chest demonstrates stable cardiomegaly",
            "portable view of the chest demonstrates mild cardiomegaly",
            "persistent severe cardiomegaly",
            "heart size is borderline enlarged",
            "cardiomegaly unchanged",
            "heart size is at the upper limits of normal",
            "redemonstration of cardiomegaly",
            "ap erect chest radiograph demonstrates the heart size is the upper limits of normal",
            "cardiac silhouette size is mildly enlarged",
            "mildly enlarged cardiac silhouette, likely left ventricular enlargement. other chambers are less prominent",
            "heart size remains at mildly enlarged",
            "persistent cardiomegaly with prominent upper lobe vessels",
        ],
        "location": [""],
    },
    "Consolidation": {
        "severity": ["", "increased", "improved", "apperance of"],
        "subtype": [
            "bilateral consolidation",
            "reticular consolidation",
            "retrocardiac consolidation",
            "patchy consolidation",
            "airspace consolidation",
            "partial consolidation",
        ],
        "location": [
            "at the lower lung zone",
            "at the upper lung zone",
            "at the left lower lobe",
            "at the right lower lobe",
            "at the left upper lobe",
            "at the right uppper lobe",
            "at the right lung base",
            "at the left lung base",
        ],
    },
    "Edema": {
        "severity": [
            "",
            "mild",
            "improvement in",
            "presistent",
            "moderate",
            "decreased",
        ],
        "subtype": [
            "pulmonary edema",
            "trace interstitial edema",
            "pulmonary interstitial edema",
        ],
        "location": [""],
    },
    "Pleural Effusion": {
        "severity": ["", "small", "stable", "large", "decreased", "increased"],
        "location": ["left", "right", "tiny"],
        "subtype": [
            "bilateral pleural effusion",
            "subpulmonic pleural effusion",
            "bilateral pleural effusion",
        ],
    },
}

COVID_TASKS = [
    'Normal',
    'COVID',
]
COVID_CLASS_PROMPTS = {
    'COVID': {
        'adjective': ['patchy','confluent'],
        'description': ['ground glass'],
        'subtype': ['opacity', 'consolidation'],
        'location': ['in peripheral', 'in mid', 'in lower'],
    }
}

RSNA_TASKS = [
    'Normal',
    'Pneumonia',
]
RSNA_CLASS_PROMPTS = {
    'Pneumonia': {
        'adjective': ['round', 'early', 'focal', 'multifocal', 'small', ''],
        'subtype': ['bacterial', 'viral', 'mycoplasma', ''],
        "location": [
            "at the mid lung zone",
            "at the upper lung zone",
            "at the right lung zone",
            "at the left lung zone",
            "at the lung bases",
            "at the right lung base",
            "at the left lung base",
            "at the bilateral lung bases",
            "at the left lower lobe",
            "at the right lower lobe",
            "at the left middle lobe",
            "at the right middle lobe",
            ""
        ]
    }
}

WEIGHTS_NAME = 'pytorch_model.bin'

# store the URL of pretrained weights, `dev` needs to change to `main` after merging it to main branch.
PRETRAINED_URL_MEDCLIP_RESNET = 'https://github.com/RyanWangZf/MedCLIP/raw/main/medclip/medclip_resnet_weight.txt'
PRETRAINED_URL_MEDCLIP_VIT = 'https://github.com/RyanWangZf/MedCLIP/raw/main/medclip/medclip_vit_weight.txt'