train_file: ['data/uw_madison_train.json'
                         
               ]
# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }               
bert_config: 'configs/config_bert.json'

image_res: 512
vision_width: 768
embed_dim: 256
batch_size: 32
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 256
patch_size: 32

#selective sampling params
selective_sampling: True
rare_grp_ratio: 0.375
batch_shuffle: False


optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 20, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 10, cooldown_epochs: 0}







